apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-monitor
spec:
  replicas: 3  # Increase replicas for high availability
  template:
    spec:
      containers:
      - name: pod-monitor
        resources:
          limits:
            cpu: "1000m"  # Increased CPU limit for production
            memory: "1Gi"  # Increased memory limit for production
          requests:
            cpu: "500m"  # Increased CPU request for production
            memory: "512Mi"  # Increased memory request for production
