apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../  # Reference the base configuration

namespace: monitoring

# Production-specific configuration
configMapGenerator:
  - name: pod-monitor-config
    behavior: merge
    literals:
      - monitoring_interval=30  # More frequent monitoring in production
      - log_level=INFO
      - pod_label_selectors=app=critical,tier=production,environment=prod
      - monitor_all_nodes=false  # Only monitor nodes with critical workloads

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: k8s-playground/pod-monitor
    newTag: stable  # Use stable tag for production
