apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitor
  namespace: monitoring
  labels:
    app: pod-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-monitor
  labels:
    app: pod-monitor
rules:
# Pod monitoring permissions
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Node monitoring permissions
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Metrics API permissions
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-monitor
  labels:
    app: pod-monitor
subjects:
- kind: ServiceAccount
  name: pod-monitor
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: pod-monitor
  apiGroup: rbac.authorization.k8s.io
